export const WAVELET_INITIALIZING = 'WAVELET_INITIALIZING'
export const WAVELET_INITIALIZED = 'WAVELET_INITIALIZED'
export const WAVELET_FAILED = 'WAVELET_FAILED'
export const WAVELET_USER_DENIED = 'WAVELET_USER_DENIED'

export const NETWORK_ID_FETCHED = 'NETWORK_ID_FETCHED'
export const NETWORK_ID_FAILED = 'NETWORK_ID_FAILED'
export const NETWORK_MISMATCH = 'NETWORK_MISMATCH'

export const NETWORK_IDS = {
    testnet: 1,
    tradenet: 3
}
